Portfolio - mobile menu branch
FredsephT32/Set-Up-Mobile-Portfolio pull request #10
Opened 2022-09-05 22:36 UTC by FredsephT32

- Implemented the required mobile features.
- Properly used JavaScript syntax.
- Use JavaScript to manipulate DOM elements.
- we make sure that there are no linter errors.
- we make sure that you used the correct GitHub flow.
- we make sure that you documented your work in a professional way.

2022-09-05 23:08 UTC, uwadonat requested changes
## Hi @FredsephT32,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- Your pull request message is very descriptive ✔️
- Well organized and clean code ✔️
- Professional readme file ✔️
![almost](https://user-images.githubusercontent.com/65860678/188519373-a358032f-0d12-4e6a-957d-538f4059afa0.jpg)
## Required Changes ♻️


_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100%.
Please, remember to tag me @uwadonat in your question so I can receive the notification.

------
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-05 23:08 UTC, uwadonat commented on index.html
> +          <a> <img src="Images/Union.png" id="Hamburger-icon" alt="Three-Lines"> </a>
- [ ] When the user clicks (or taps) the hamburger button, the mobile menu should appears. For now nothing happens. kindly fix this.
![ha](https://user-images.githubusercontent.com/65860678/188519190-5e751f1f-77c1-43c5-a81b-1c94b3f91424.PNG)

2022-09-06 00:11 UTC, FredsephT32 commented
I don't understand the reviewer [uwadonat](https://github.com/uwadonat) because I double check my "mobile-menu" branch and when I click the hamburger button it works perfectly. 

Probably  [uwadonat](https://github.com/uwadonat)  did not review my last commit.

2022-09-06 00:23 UTC, Reem-lab approved these changes
# Hi @FredsephT32,👋🏻👋🏻

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉🔥🔥💯💯
<img src="https://media1.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>


## Highlights ✨✨
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Great working on the functionality✅
📌 Good commit messages ✅
📌 Professional README ✅

## Optional suggestions
- [ OPTIONAL ] I think it would be great if you blur the background since it is blured in the Figma template so please blur it and remove the scroll in the side since it is not found in the Figma as well 🔥🚀💯😊

- Your design
![image](https://user-images.githubusercontent.com/58553711/188523197-b748667c-520c-4a76-8057-b5a02863a7b4.png)

- Original design
![image](https://user-images.githubusercontent.com/58553711/188523219-36a88f3d-88b8-4e11-abfd-70e7f9996d51.png)


_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-06 00:46 UTC, FredsephT32 commented
Thank you [Reem-lab](https://github.com/Reem-lab) for approving my pull request!

2022-09-06 00:47 UTC, merged